# wallust.toml needs to include this
# alacritty = { template = 'alacritty.toml', target = '~/.config/alacritty/colors.toml' }
# and alacritty.toml should import that file under [general]
[colors.primary]
background = "#002B36"
foreground = "#839496"

[colors.normal]
black   = "#073642"
red     = "#DC322F"
green   = "#859900"
yellow  = "#CF9A6B"
blue    = "#268BD2"
magenta = "#D33682"
cyan    = "#2AA198"
white   = "#EEE8D5"

[colors.bright]
black   = "#657B83"
red     = "#CB4B16"
green   = "#859900"
yellow  = "#CF9A6B"
blue    = "#6C71C4"
magenta = "#D33682"
cyan    = "#2AA198"
white   = "#FDF6E3"
