# wallust.toml needs to include this
# alacritty = { template = 'alacritty.toml', target = '~/.config/alacritty/colors.toml' }
# and alacritty.toml should import that file under [general]
[colors.primary]
background = "#06060B"
foreground = "#ADADB3"

[colors.normal]
black   = "#53504F"
red     = "#4A4A56"
green   = "#747B93"
yellow  = "#95758B"
blue    = "#AEB2CF"
magenta = "#F5A3B9"
cyan    = "#7AD4FB"
white   = "#82828A"

[colors.bright]
black   = "#5B5B60"
red     = "#4A4A56"
green   = "#747B93"
yellow  = "#95758B"
blue    = "#AEB2CF"
magenta = "#F5A3B9"
cyan    = "#7AD4FB"
white   = "#82828A"
