cursor #B4B5B6

foreground #ADAEAE
background #070708

# black
color0  #515252
color8  #5B5B5C

# red
color1  #4B4B4D
color9  #4B4B4D

# green
color2  #6C6C6E
color10 #6C6C6E

# yellow
color3  #7A7B7D
color11 #7A7B7D

# blue
color4  #8E8F91
color12 #8E8F91

# magenta
color5  #BBBCBE
color13 #BBBCBE

# cyan
color6  #EEF0F2
color14 #EEF0F2

# white
color7  #828384
color15 #828384
