cursor #D1A8B6

foreground #ADADB3
background #06060B

# black
color0  #53504F
color8  #5B5B60

# red
color1  #4A4A56
color9  #4A4A56

# green
color2  #747B93
color10 #747B93

# yellow
color3  #95758B
color11 #95758B

# blue
color4  #AEB2CF
color12 #AEB2CF

# magenta
color5  #F5A3B9
color13 #F5A3B9

# cyan
color6  #7AD4FB
color14 #7AD4FB

# white
color7  #82828A
color15 #82828A
